version: '2'
services:
   mysql:
      image: mysql
      ports:
       - "3306:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=cats
   redis:
      image: redis
      ports:
       - "6379:6379"
   mongo:
      image: mongo
      ports:
       - "27017:27017"
   rabbitmq:
      image: rabbitmq:3-management
      ports:
       - "4369:4369"
       - "5671:5671"
       - "5672:5672"
       - "15671:15671"
       - "15672:15672"
